<a href="https://colab.research.google.com/github/RibhuMitra/Machine-Learning-Using-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Numpy

In [ ]:
import numpy as np


List Vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
from time import process_time

python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0014245890000008643


Time Taken By Numpy Array

In [ ]:
import numpy as np

np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00046400899999987644


Time Difference is Significant when we work with large datasets.

In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#Create a 1 dimensional array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

4 columns and 1 row(1-D Array).

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
b = np.array([(1,2,3,4),(5,6,7,8)])
b.shape

(2, 4)

2 rows and 4 columns.

Initial Placeholders in numpy arrays
