<a href="https://colab.research.google.com/github/RibhuMitra/Machine-Learning-Using-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Numpy

In [ ]:
import numpy as np


List Vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
from time import process_time

python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0014245890000008643


Time Taken By Numpy Array

In [ ]:
import numpy as np

np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00046400899999987644


Time Difference is Significant when we work with large datasets.

In [ ]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#Create a 1 dimensional array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a.shape

(4,)

4 columns and 1 row(1-D Array).

In [ ]:
#2-D Array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np
b = np.array([(1,2,3,4),(5,6,7,8)])
b.shape

(2, 4)

2 rows and 4 columns.

Initial Placeholders in numpy arrays


In [2]:
# Create a numpy array of Zeros
import numpy as np
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
# Create a numpy array of Ones
import numpy as np
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
# Array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [8]:
#Create an identity matrix.
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
# create a numpy array with random variables.
a = np.random.random((3,4))
print(a) # all the values will be between 0s and 1s

[[0.63102922 0.78076622 0.94835187 0.49034738]
 [0.15608707 0.81989357 0.43195696 0.27547987]
 [0.19082235 0.87940462 0.31457498 0.53366393]]


In [10]:
# random integer values array within a specific range
c = np.random.randint(10,100, (3,5))
print(c)

[[39 88 98 50 36]
 [79 21 83 53 32]
 [12 73 73 55 73]]


In [11]:
# array of evenly spaced values
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [12]:
# convert a list to a numpy array
list1 = [10,20,20,20,50]

np_array = np.array(list1)
print(np_array)
type(np_array)


[10 20 20 20 50]


numpy.ndarray

Analyzing a numpy array

In [13]:
c = np.random.randint(10,90, (5,5))
print(c)

[[77 49 62 58 42]
 [75 15 48 69 71]
 [87 45 46 75 35]
 [14 40 89 29 48]
 [39 61 46 76 11]]


In [14]:
# array dimension
print(c.shape)

(5, 5)


In [15]:
#number of dimensions
print(c.ndim)

2


In [16]:
# number of elements in an array
print(c.size)

25


In [17]:
# checking the datatype of the values in the array
print(c.dtype)

int64


int - 64 bit

Mathematical operations on a np array

In [18]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) # concatenates two list
# element wise addition is not possible

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [19]:
a = np.random.randint(0,10, (3,3))
b = np.random.randint(10,20, (3,3))
print(a)
print(b)

[[8 1 4]
 [4 8 4]
 [8 5 4]]
[[19 17 15]
 [15 14 15]
 [18 18 19]]


In [20]:
print(a+b)
print(a*b)
print(a-b)
print(a/b)

[[27 18 19]
 [19 22 19]
 [26 23 23]]
[[152  17  60]
 [ 60 112  60]
 [144  90  76]]
[[-11 -16 -11]
 [-11  -6 -11]
 [-10 -13 -15]]
[[0.42105263 0.05882353 0.26666667]
 [0.26666667 0.57142857 0.26666667]
 [0.44444444 0.27777778 0.21052632]]


In [21]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

# performing arithmetic functions using library functions

[[27 18 19]
 [19 22 19]
 [26 23 23]]
[[-11 -16 -11]
 [-11  -6 -11]
 [-10 -13 -15]]
[[152  17  60]
 [ 60 112  60]
 [144  90  76]]
[[0.42105263 0.05882353 0.26666667]
 [0.26666667 0.57142857 0.26666667]
 [0.44444444 0.27777778 0.21052632]]


Array Manipulation

In [22]:
array = np.random.randint(0,10, (2,3))
print(array)
print(array.shape)

[[7 5 9]
 [9 2 7]]
(2, 3)


In [23]:
# transpose
trans = np.transpose(array)
print(trans)
print(array.shape)

[[7 9]
 [5 2]
 [9 7]]
(2, 3)


In [24]:
array = np.random.randint(0,10, (2,3))
print(array)
print(array.shape)

[[3 4 6]
 [2 9 2]]
(2, 3)


In [25]:
trans2 = array.T
print(trans2)
print(trans2.shape)

# using .T function to find transpose

[[3 2]
 [4 9]
 [6 2]]
(3, 2)


In [26]:
# reshaping a array
a = np.random.randint(0,10, (2,3))
print(a)
print(a.shape)

[[7 2 1]
 [7 0 7]]
(2, 3)


In [33]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 2]
 [1 7]
 [0 7]]
(3, 2)
